#!/usr/bin/env bash
# deploy_magic_mirror.sh — deploy the MMM-HailoVision module into a local
# MagicMirror² install.
#
# Each run refreshes the previous deployment:
#   1. Copies the module files (this repo, honoring .gitignore) over the existing
#      MMM-HailoVision module folder in the install, overwriting changed
#      files and adding new ones. The folder is NOT deleted first, so any local
#      files there (e.g. node_modules) are preserved.
#   2. Re-injects the module block from config.example.js (at the repo root)
#      into MagicMirror's config/config.js, replacing any block injected by a
#      previous run (other modules in the config are left untouched).
#   3. If MagicMirror is currently running, it is stopped and (when it was
#      running) restarted so it picks up the new module + config.
#
# Usage:
#   scripts/deploy_magic_mirror.sh [MM_DIR]
#
# Environment / arguments:
#   MM_DIR       MagicMirror install dir (default: ~/Documents/repos/MagicMirror)
#                May also be passed as the first positional argument.
#   --no-restart Deploy only; never (re)start MagicMirror.
#   --restart    Always start MagicMirror after deploy, even if it was not running.
#   --stop       Stop MagicMirror and exit immediately (no deploy).

set -euo pipefail

# --- Resolve paths ----------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

MM_DIR="${MM_DIR:-$HOME/Documents/repos/MagicMirror}"
RESTART_MODE="auto"   # auto | always | never
STOP_ONLY="false"

for arg in "$@"; do
    case "$arg" in
        --no-restart) RESTART_MODE="never" ;;
        --restart)    RESTART_MODE="always" ;;
        --stop)       STOP_ONLY="true" ;;
        -*)           echo "❌ Unknown option: $arg" >&2; exit 2 ;;
        *)            MM_DIR="$arg" ;;
    esac
done

# The whole repo IS the MagicMirror module (the module files live at the repo
# root, with the hailo/ backend alongside them), so the repo is copied into
# MagicMirror's modules/ dir — honoring .gitignore, so build artifacts, the
# venv, the resources symlink, and .git/ are left out (see the copy step below).
SRC_MODULE_DIR="$REPO_ROOT"
DEST_MODULE_DIR="$MM_DIR/modules/MMM-HailoVision"
CONFIG_FILE="$MM_DIR/config/config.js"
EXAMPLE_CONFIG="$SRC_MODULE_DIR/config.example.js"

START_MARKER='/* >>> MMM-HailoVision managed block (auto-generated by deploy_magic_mirror.sh) >>> */'
END_MARKER='/* <<< MMM-HailoVision managed block <<< */'
MARKER_NEEDLE_START='>>> MMM-HailoVision managed block'
MARKER_NEEDLE_END='<<< MMM-HailoVision managed block'

# --- Validate ---------------------------------------------------------------
[[ -f "$SRC_MODULE_DIR/MMM-HailoVision.js" ]] || { echo "❌ Module entry not found: $SRC_MODULE_DIR/MMM-HailoVision.js" >&2; exit 1; }
[[ -f "$EXAMPLE_CONFIG" ]]   || { echo "❌ Example config not found: $EXAMPLE_CONFIG" >&2; exit 1; }
[[ -d "$MM_DIR" ]]          || { echo "❌ MagicMirror install not found: $MM_DIR" >&2; exit 1; }
[[ -f "$CONFIG_FILE" ]]    || { echo "❌ MagicMirror config not found: $CONFIG_FILE" >&2; exit 1; }

echo "📦 Repo:          $REPO_ROOT"
echo "🪞 MagicMirror:   $MM_DIR"

# --- Detect a running MagicMirror -------------------------------------------
# Returns the management method via the MM_RUN_METHOD global: pm2 | proc | none
MM_RUN_METHOD="none"

# Print the PIDs of MagicMirror processes that actually belong to THIS install,
# i.e. whose working directory resolves to $MM_DIR. This avoids matching
# unrelated processes that merely mention "electron"/"serveronly" on their
# command line (including the shell that launched this script).
mm_pids() {
    local mm_real pid cwd
    mm_real="$(realpath "$MM_DIR" 2>/dev/null || echo "$MM_DIR")"
    { pgrep -f "js/electron.js" || true; pgrep -f "serveronly" || true; } | sort -un | while read -r pid; do
        [[ -n "$pid" ]] || continue
        cwd="$(realpath "/proc/$pid/cwd" 2>/dev/null)" || continue
        [[ "$cwd" == "$mm_real" ]] && echo "$pid"
    done
}

detect_running() {
    if command -v pm2 &>/dev/null && pm2 jlist 2>/dev/null | grep -q '"MagicMirror"'; then
        MM_RUN_METHOD="pm2"
        return
    fi
    if [[ -n "$(mm_pids)" ]]; then
        MM_RUN_METHOD="proc"
        return
    fi
    MM_RUN_METHOD="none"
}

stop_running() {
    case "$MM_RUN_METHOD" in
        pm2)
            echo "🛑 Stopping MagicMirror (pm2)…"
            pm2 stop MagicMirror >/dev/null
            ;;
        proc)
            echo "🛑 Stopping MagicMirror (electron/node)…"
            local pids
            pids=$(mm_pids | tr '\n' ' ')
            [[ -n "${pids// }" ]] && kill $pids 2>/dev/null || true
            sleep 2
            for pid in $pids; do
                kill -0 "$pid" 2>/dev/null && kill -KILL "$pid" 2>/dev/null || true
            done
            ;;
    esac
}

start_mm() {
    case "$MM_RUN_METHOD" in
        pm2)
            echo "▶️  Restarting MagicMirror (pm2)…"
            pm2 restart MagicMirror >/dev/null
            ;;
        *)
            local logfile="$MM_DIR/magicmirror.log"
            echo "▶️  Starting MagicMirror (npm start)…"
            echo "📝 Logs (incl. [hailo] Python pipeline output) → $logfile"
            ( cd "$MM_DIR" && DISPLAY="${DISPLAY:-:0}" nohup npm start >"$logfile" 2>&1 & )
            ;;
    esac
}

detect_running
WAS_RUNNING="$MM_RUN_METHOD"
[[ "$WAS_RUNNING" != "none" ]] && stop_running

# --stop: stop MagicMirror only, then exit without deploying.
if [[ "$STOP_ONLY" == "true" ]]; then
    if [[ "$WAS_RUNNING" == "none" ]]; then
        echo "ℹ️  MagicMirror was not running; nothing to stop."
    else
        echo "✅ MagicMirror stopped."
    fi
    exit 0
fi

# --- 1. Copy the module files (overlay onto existing dir) -------------------
echo "📋 Copying repo (excluding gitignored files) into: $DEST_MODULE_DIR"
mkdir -p "$DEST_MODULE_DIR"
if git -C "$SRC_MODULE_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    # git ls-files -c -o --exclude-standard = tracked + untracked files, minus
    # everything .gitignore (and .git/) excludes. -z / --null keeps unusual
    # filenames safe. Piped through tar to recreate the tree under DEST.
    # --ignore-failed-read: a tracked file that was deleted on disk but whose
    # deletion isn't committed yet still shows up in ls-files; skip it (warn)
    # instead of aborting the whole deploy under `set -o pipefail`.
    git -C "$SRC_MODULE_DIR" ls-files -z --cached --others --exclude-standard \
      | tar -C "$SRC_MODULE_DIR" --null -T - --ignore-failed-read -cf - \
      | tar -C "$DEST_MODULE_DIR" -xf -
else
    echo "⚠️  Not a git repo; copying everything (including otherwise-ignored files)."
    cp -a "$SRC_MODULE_DIR/." "$DEST_MODULE_DIR/"
fi

# --- 2. Re-inject the config block ------------------------------------------
echo "⚙️  Updating config: $CONFIG_FILE"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

BLOCK_FILE="$TMP_DIR/block.js"
{
    printf '\t\t%s\n' "$START_MARKER"
    # Strip the leading explanatory /* … */ comment from the example file and
    # keep only the module object (from the first line starting with "{").
    awk 'started || /^[[:space:]]*\{/ { started=1; print }' "$EXAMPLE_CONFIG"
    printf '\t\t,\n'
    printf '\t\t%s\n' "$END_MARKER"
} > "$BLOCK_FILE"

# Remove any previously-injected managed block (range between the markers).
STRIPPED="$TMP_DIR/config.stripped.js"
awk -v s="$MARKER_NEEDLE_START" -v e="$MARKER_NEEDLE_END" '
    index($0, s) { skip=1 }
    !skip { print }
    index($0, e) { skip=0 }
' "$CONFIG_FILE" > "$STRIPPED"

# Insert the fresh block right after the top-level "modules: [" line.
NEWCONF="$TMP_DIR/config.new.js"
awk -v bf="$BLOCK_FILE" '
    !ins && /^[[:space:]]*modules:[[:space:]]*\[[[:space:]]*$/ {
        print
        while ((getline line < bf) > 0) print line
        close(bf)
        ins=1
        next
    }
    { print }
    END { if (!ins) { print "ERR_NO_MODULES_ARRAY" > "/dev/stderr"; exit 3 } }
' "$STRIPPED" > "$NEWCONF" || {
    echo "❌ Could not find the top-level 'modules: [' array in $CONFIG_FILE" >&2
    exit 3
}

# Validate the generated config is syntactically valid JS before installing it.
if command -v node &>/dev/null; then
    if ! node --check "$NEWCONF" 2>"$TMP_DIR/node.err"; then
        echo "❌ Generated config failed syntax check; leaving existing config untouched:" >&2
        cat "$TMP_DIR/node.err" >&2
        exit 4
    fi
fi

cp "$CONFIG_FILE" "$CONFIG_FILE.deploy.bak"
cp "$NEWCONF" "$CONFIG_FILE"
echo "💾 Backed up previous config to: $CONFIG_FILE.deploy.bak"

# --- 3. (Re)start MagicMirror -----------------------------------------------
case "$RESTART_MODE" in
    never)
        echo "⏭️  Skipping restart (--no-restart)."
        ;;
    always)
        [[ "$WAS_RUNNING" == "none" ]] && MM_RUN_METHOD="none"
        start_mm
        ;;
    auto)
        if [[ "$WAS_RUNNING" != "none" ]]; then
            start_mm
        else
            echo "ℹ️  MagicMirror was not running; not starting it. Use --restart to start."
        fi
        ;;
esac

echo "✅ Deploy complete."
